# -*- coding: utf-8 -*-
"""Project on CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5BbndMEIifW0qUVB-bj3bc-Sv2mnFTI
"""

import os
import numpy

import zipfile
zip_path = "/content/project on CNN (1).zip"
extract_path = "/content/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(extract_path)

!unrar x "/content/DATASET - LMS (3) (1).rar" "/content/"
print('/content/')

import tensorflow as tf

train = tf.keras.utils.image_dataset_from_directory(
    "/content/DATASET/train",

    image_size = (256,256),
    batch_size = 32,
    shuffle = True)

test = tf.keras.utils.image_dataset_from_directory(
    "/content/DATASET/test",

    image_size = (256,256),
    batch_size = 32,
    shuffle = True)

val = tf.keras.utils.image_dataset_from_directory(
    "/content/DATASET/val",

    image_size = (256,256),
    batch_size = 32,
    shuffle = True)

import matplotlib.pyplot as plt

batch = next(iter(train))

fig,axes = plt.subplots(4,4,figsize = (10,10))
for i, ax in enumerate(axes.flat):
  ax.imshow(batch[0][i]/255.0)
  label_idx = batch[1][i].numpy()
  label_map = {i:name for i,name in enumerate(train.class_names)}
  ax.set_title(label_map[label_idx])
  ax.axis("off")
plt.show()

normalize = tf.keras.layers.Rescaling(0.1/255.0)

train = train.map(lambda x,y:(normalize(x),y))
test = test.map(lambda x,y:(normalize(x),y))
val = val.map(lambda x,y:(normalize(x),y))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout,BatchNormalization

import numpy as np
from collections import Counter

labels = []

for _, y in train:
    labels.extend(y.numpy())

print(Counter(labels))

import tensorflow as tf
from tensorflow.keras import layers

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.RandomContrast(0.1)
])

model = Sequential()

model.add(data_augmentation)
model.add(Conv2D(32,kernel_size=(3,3),activation = "relu",input_shape = (256,256,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Conv2D(64,kernel_size=(3,3),activation = "relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
#model.add(Dense(128,activation = "relu"))
model.add(Dense(64,activation = "relu"))
model.add(Dense(3,activation = "softmax"))

model.compile(optimizer = "adam",loss = "sparse_categorical_crossentropy",metrics = ["accuracy"])

model.summary()

from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau

early_stop = EarlyStopping(monitor = "val_loss",patience =5, restore_best_weights = True)
reduce_lr = ReduceLROnPlateau(monitor = "val_loss",patience = 3, factor = 0.5,min_lr = 1e-6)

#model.compile(optimizer = "adam",loss = "sparse_categorical_crossentropy",metrics = ["accuracy"])

model.fit(train,batch_size= 32 ,epochs = 30,validation_data = val)#,callbacks = [early_stop,reduce_lr])



